# Generated by Django 5.1.5 on 2025-02-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipesmodels",
            name="cover",
            field=models.ImageField(
                blank=True, null=True, upload_to="recipes/cover/%y/%m/%d"
            ),
        ),
        migrations.AlterField(
            model_name="recipesmodels",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
