# Generated by Django 5.1.5 on 2025-03-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_recipesmodels_cover_alter_recipesmodels_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipesmodels",
            name="description",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
